Sprint 1 professionals
tiagofunk/projetodepe pull request #11
Opened 2023-01-12 16:16 UTC by tiagofunk

2023-01-13 01:06 UTC, Raphael-Ramalho requested changes

2023-01-13 01:06 UTC, Raphael-Ramalho commented on src/components/Professionals/Professionals.tsx
> +  const PROFESSIONALS = [
no mercado, variável sempre deve estar em camelCase. N estar em camelCase n gerará nenhum problema para o nosso código, mas vale a pena se acostumar com isso pq essas convenções facilitam o entendimento de outros programadores que olharem o seu código

2023-01-13 01:06 UTC, Raphael-Ramalho commented on src/components/Professionals/Professionals.tsx
> +  ];
Quando vc estiver trabalhando com estruturas com multiplos niveis, de preferência pela estrutura de objetos. Como no exemplo a seguir:

```
const professionals = [
     {photo: foto_luana, name: "Luana", expertise: "Idealizadora"},
     {photo: foto_luana, name: "Luana", expertise: "Idealizadora"}, 
     {photo: foto_luana, name: "Luana", expertise: "Idealizadora"}
]
```

Isso irá facilitar a manipulação dessas informações e tornará essa manipulação mais legivel

2023-01-13 01:06 UTC, Raphael-Ramalho commented on src/components/Professionals/Professionals.tsx
> +					{createBox(2,professionals[2][0],professionals[2][1],professionals[2][2])}
utilizando a estrutura de objetos, vc poderia refatorar essas linhas da seguinte forma utilizando metodos de manipulação de arrays e objetos: 

```
professionals.map((person, index)=>{
      return (
	   <BoxArea>	
                <BoxPrimary isEven={index % 2 === 0}>	
                     <BoxImage src={person.photo} alt={""} />
                     <BoxTitle>{person.name}</BoxTitle>
                     <BoxText>{person.expertise}</BoxText>
                </BoxPrimary>
           </BoxArea>
      )
}
```

2023-01-13 01:15 UTC, Raphael-Ramalho requested changes

2023-01-13 01:15 UTC, Raphael-Ramalho commented on src/components/Professionals/Professionals.style.ts
> +`;
Logica para aplicar a propriedade isEven a fim de trocar o background dinamicamente:

coloque a interface em um arquivo de tipos
```
export interface BoxProps {
      isEven: boolean;
}

export const BoxPrimary = styled.div<BoxProps>`
      ${StyleBox}
      background-color: ${({isEven}) => isEven ? colors.secondary : colors.terciary }
`
```

2023-01-13 17:06 UTC, tiagofunk commented on src/components/Professionals/Professionals.tsx
> +  const PROFESSIONALS = [
Entendi, em linguagens como Java e C++, constantes são identificadas com todas as letras maiúsculas.

2023-01-15 16:34 UTC, Raphael-Ramalho approved these changes

2023-01-15 19:12 UTC, merged