TimeLine addition
tiagofunk/projetodepe pull request #8
Opened 2023-01-09 02:05 UTC by tiagofunk

2023-01-09 04:49 UTC, Raphael-Ramalho commented
A timeline está muito bonita, mas o tamanho dela irá prejudicar a utilização do site. seria possível adicionar um scroll no conteúdo abaixo do titulo?

2023-01-10 03:05 UTC, tiagofunk commented
Fiz a alteração

2023-01-10 23:02 UTC, Raphael-Ramalho requested changes

2023-01-10 23:02 UTC, Raphael-Ramalho commented on src/components/Timeline/Timeline.style.ts
> +  overflow-y: scroll;
adicione a propriedade `overflow-x: hidden` também

2023-01-11 12:41 UTC, merged